"""Human-facing /analysis page — the F1 framing/emotion/sentiment view.

Hirspektrum-style analytical dashboard rendered from the classifier columns:
frame-distribution donut (Semetko–Valkenburg 9 frames), emotion bars (Plutchik),
sentiment gauge, and a per-source breakdown. Pure inline SVG, themed via CSS
vars (day/night), no JS beyond the theme toggle. Data comes from
echolot_analytics.overview().

2026-06-12 (UX-teszter #7+#10): lokalizált felület (HU/EN, más nyelv → EN),
közös nav-strip, és kinyitható módszertani magyarázat arról, MI ALAPJÁN
számít egy cikk pozitívnak/negatívnak, és hogyan olvasandó a forrás-tábla.
"""
from __future__ import annotations

import math
from html import escape as _esc
from echolot_theme import (theme_html_attr, theme_toggle_html,
                           THEME_TOGGLE_CSS, THEME_TOGGLE_JS)

_FRAME_COLOR = {
    "conflict": "#f85149", "human_interest": "#58a6ff", "economic": "#3fb950",
    "morality": "#bc8cff", "vulnerability": "#d29922", "responsibility": "#ff7b72",
    "security_threat": "#db61a2", "progress": "#2ea043", "crime": "#e3633d",
    "other": "#8b949e",
}
_FRAME_LABEL = {
    "hu": {
        "conflict": "Konfliktus", "human_interest": "Emberi érdek", "economic": "Gazdasági",
        "morality": "Erkölcs", "vulnerability": "Kiszolgáltatottság",
        "responsibility": "Felelősség", "security_threat": "Biztonsági fenyegetés",
        "progress": "Fejlődés", "crime": "Bűncselekmény", "other": "Egyéb",
    },
    "en": {
        "conflict": "Conflict", "human_interest": "Human interest", "economic": "Economic",
        "morality": "Morality", "vulnerability": "Vulnerability", "responsibility": "Responsibility",
        "security_threat": "Security threat", "progress": "Progress",
        "crime": "Crime", "other": "Other",
    },
}
_EMO_COLOR = {
    "anger": "#f85149", "fear": "#8957e5", "joy": "#e3b341", "surprise": "#39c5cf",
    "sadness": "#1f6feb", "trust": "#3fb950", "disgust": "#db61a2", "other": "#8b949e",
}
_EMO_LABEL = {
    "hu": {"anger": "düh", "fear": "félelem", "joy": "öröm", "surprise": "meglepetés",
           "sadness": "szomorúság", "trust": "bizalom", "disgust": "undor", "other": "egyéb"},
    "en": {},  # angolul a nyers kulcs jó
}

# UI-szövegek — HU teljes, minden más nyelv az EN-re esik.
_L = {
    "subtitle":        {"hu": "framing- és érzelem-elemzés", "en": "framing & emotion analysis"},
    "framing":         {"hu": "Framing — Semetko–Valkenburg", "en": "Framing — Semetko–Valkenburg"},
    "emotion":         {"hu": "Érzelmek — Plutchik", "en": "Emotion — Plutchik"},
    "sentiment":       {"hu": "Összesített hangulat", "en": "Overall sentiment"},
    "sources":         {"hu": "Forrás-bontás", "en": "Source breakdown"},
    "articles":        {"hu": "cikk", "en": "articles"},
    "no_emotion":      {"hu": "még nincs érzelem-adat", "en": "no emotion data yet"},
    "no_sentiment":    {"hu": "még nincs hangulat-adat", "en": "no sentiment data yet"},
    "no_sources":      {"hu": "még nincs forrás-adat", "en": "no sources yet"},
    "range":           {"hu": "tartomány", "en": "range"},
    "over_n":          {"hu": "osztályozott cikk alapján", "en": "classified articles"},
    "th_source":       {"hu": "Forrás", "en": "Source"},
    "th_lean":         {"hu": "Beállítottság", "en": "Lean"},
    "th_articles":     {"hu": "Cikk", "en": "Art."},
    "th_frame":        {"hu": "Domináns frame", "en": "Dominant frame"},
    "th_sentiment":    {"hu": "Hangulat", "en": "Sentiment"},
    "empty_window":    {"hu": "Ebben az időablakban még nincs osztályozott cikk.<br>"
                              "Az F1-osztályozó a háttérben folyamatosan dolgozik — "
                              "az oldal magától megtelik.",
                        "en": "No classified articles in this window yet.<br>"
                              "The F1 classifier fills framing/emotion/sentiment in the "
                              "background — this view lights up as it runs."},
    "placeholder":     {"hu": "Téma-szűrő (opcionális) — pl. 'migráció', 'Magyar Péter'",
                        "en": "Topic filter (optional) — e.g. 'migration', 'Magyar Péter'"},
    "analyze":         {"hu": "Elemzés", "en": "Analyze"},
    "days":            {"hu": "nap", "en": "days"},
    "foot":            {"hu": "Echolot — framing, érzelem és hangulat 93 médiaszférán át.",
                        "en": "Generated by Echolot — framing, emotion & sentiment across 93 media spheres."},
    "scope_local":     {"hu": "🏠 Magyar sajtó", "en": "🏠 Local-language press"},
    "scope_global":    {"hu": "🌍 Globális — minden forrás", "en": "🌍 Global — all sources"},
    "method_q":        {"hu": "Mi alapján pozitív vagy negatív? Hogyan olvasd a táblázatot?",
                        "en": "What makes an article positive or negative? How to read the table?"},
    "method_body":     {"hu": "<p><strong>Hangulat (−1.0 … +1.0):</strong> minden cikket egy "
                              "nyelvi modell (F1-osztályozó) pontoz a cikk <em>hangvétele</em> "
                              "alapján — a −1.0 erősen negatív, a 0 semleges, a +1.0 erősen "
                              "pozitív tálalást jelent. Nem a téma 'jóságát' méri, hanem azt, "
                              "hogy a szöveg hogyan tálalja.</p>"
                              "<p><strong>A forrás-táblázat</strong> forrásonként mutatja a "
                              "cikkszámot, a leggyakoribb frame-et és az átlag-hangulatot — "
                              "így látszik, ha ugyanazt a témát az egyik oldal pozitívan, a "
                              "másik negatívan tálalja. A <em>beállítottság</em> (lean) "
                              "kézzel karbantartott forrás-besorolás, nem AI-döntés "
                              "(módszertan a főoldali jelmagyarázatban).</p>",
                        "en": "<p><strong>Sentiment (−1.0 … +1.0):</strong> every article is "
                              "scored by a language model (the F1 classifier) based on the "
                              "article's <em>tone</em> — −1.0 is strongly negative, 0 neutral, "
                              "+1.0 strongly positive framing. It measures how the text frames "
                              "the topic, not whether the topic is 'good'.</p>"
                              "<p><strong>The source table</strong> shows per-source article "
                              "counts, the dominant frame and average sentiment — revealing "
                              "when one side covers the same topic positively and the other "
                              "negatively. <em>Lean</em> is a manually curated source rating, "
                              "not an AI decision (methodology in the front-page legend).</p>"},
}


def _t(key: str, lang: str) -> str:
    d = _L[key]
    return d.get(lang) or d["en"]


def _frame_label(frame: str, lang: str) -> str:
    table = _FRAME_LABEL["hu"] if lang == "hu" else _FRAME_LABEL["en"]
    return table.get(frame) or _FRAME_LABEL["en"].get(frame, frame)


def _emo_label(emo: str, lang: str) -> str:
    if lang == "hu":
        return _EMO_LABEL["hu"].get(emo, emo)
    return emo


_CSS = """
:root{--bg:#0a0d12;--panel:#11151c;--panel2:#161b22;--border:rgba(255,255,255,.10);--text:#e8eef0;
  --muted:#8a9499;--accent:#14b8a6;--grey:#161b22;--text-dim:#8a9499;--bg-card:#11151c}
[data-theme="day"]{--bg:#f7f4ed;--panel:#fff;--panel2:#f1ede3;--border:rgba(26,24,20,.12);
  --text:#1a1814;--muted:#6b6459;--accent:#0f766e;--grey:#f1ede3;--text-dim:#6b6459;--bg-card:#fff}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);
  font:15px/1.55 -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Arial,sans-serif}
.scope-row{display:flex;gap:.5rem;margin:0 0 1rem}
.scope-btn{font-size:.78rem;padding:.3rem .8rem;border-radius:999px;
  border:1px solid var(--border);color:var(--muted);text-decoration:none}
.scope-btn:hover{border-color:var(--accent);color:var(--text)}
.scope-btn.active{border-color:var(--accent);color:var(--accent);font-weight:600}
.src-link{color:var(--text);text-decoration:none;border-bottom:1px dotted var(--muted)}
.src-link:hover{color:var(--accent);border-bottom-color:var(--accent)}
a{color:var(--accent);text-decoration:none}
.wrap{max-width:920px;margin:0 auto;padding:28px 20px 80px}
.topbar{display:flex;justify-content:space-between;align-items:center;margin-bottom:22px}
.brand{font-weight:700;font-size:20px}.brand small{color:var(--muted);font-weight:400;font-size:13px}
.tt{background:var(--panel);border:1px solid var(--border);color:var(--text);border-radius:8px;
  padding:6px 12px;cursor:pointer;font-size:13px}
form.q{display:flex;gap:10px;flex-wrap:wrap;background:var(--panel);border:1px solid var(--border);
  border-radius:12px;padding:14px;margin-bottom:22px}
form.q input{flex:1;min-width:240px;background:var(--panel2);border:1px solid var(--border);
  color:var(--text);border-radius:8px;padding:10px 12px;font-size:15px}
form.q select,form.q button{background:var(--panel2);border:1px solid var(--border);color:var(--text);
  border-radius:8px;padding:10px 12px;font-size:14px;cursor:pointer}
form.q button{background:var(--accent);color:#fff;border:none;font-weight:600;padding:10px 20px}
.grid{display:grid;grid-template-columns:1fr 1fr;gap:16px;margin-bottom:16px}
@media(max-width:680px){.grid{grid-template-columns:1fr}}
.card{background:var(--panel);border:1px solid var(--border);border-radius:12px;padding:18px 20px;margin-bottom:16px}
.card h3{margin:0 0 14px;font-size:13px;text-transform:uppercase;letter-spacing:1px;color:var(--muted)}
.donut-wrap{display:flex;gap:18px;align-items:center;flex-wrap:wrap}
.legend{display:flex;flex-direction:column;gap:6px;font-size:13px;flex:1;min-width:160px}
.legend .row{display:flex;align-items:center;gap:8px}
.legend .sw{width:11px;height:11px;border-radius:3px;flex:0 0 auto}
.legend .pct{margin-left:auto;color:var(--muted);font-variant-numeric:tabular-nums}
.ebar{display:flex;align-items:center;gap:10px;margin:7px 0;font-size:13px}
.ebar .lab{width:90px;color:var(--muted)}
.ebar .track{flex:1;height:9px;background:var(--grey);border-radius:5px;overflow:hidden}
.ebar .fill{display:block;height:100%;border-radius:5px}
.ebar .n{width:30px;text-align:right;color:var(--muted);font-variant-numeric:tabular-nums}
.senti{display:flex;align-items:center;gap:12px}
.senti .big{font-size:34px;font-weight:700}
.gauge{flex:1;height:10px;border-radius:6px;background:linear-gradient(90deg,#f85149,#d29922,#3fb950);position:relative}
.gauge .pin{position:absolute;top:-4px;width:4px;height:18px;background:var(--text);border-radius:2px;transform:translateX(-2px)}
table{width:100%;border-collapse:collapse;font-size:13.5px}
th{text-align:left;color:var(--muted);font-weight:600;font-size:12px;text-transform:uppercase;
  letter-spacing:.5px;padding:6px 8px;border-bottom:1px solid var(--border)}
td{padding:8px;border-bottom:1px solid var(--border)}
.chip{font-size:11.5px;padding:3px 8px;border-radius:6px;color:#fff;white-space:nowrap}
.sent-cell{font-variant-numeric:tabular-nums}
.cov{color:var(--muted);font-size:12.5px;margin-bottom:18px}
.empty{color:var(--muted);text-align:center;padding:40px 0}
.foot{color:var(--muted);font-size:12.5px;text-align:center;margin-top:30px;padding-top:18px;border-top:1px solid var(--border)}
details.method{background:var(--panel);border:1px dashed var(--border);border-radius:12px;
  padding:10px 16px;margin-bottom:16px;font-size:13.5px;color:var(--muted)}
details.method summary{cursor:pointer;color:var(--accent);font-weight:600}
details.method p{margin:10px 0 0;line-height:1.55}
details.method strong{color:var(--text)}
"""

_THEME_JS = """(function(){var k='echolot-theme';function set(t){
document.documentElement.setAttribute('data-theme',t);try{localStorage.setItem(k,t)}catch(e){}
var b=document.getElementById('tt');if(b)b.textContent=t==='day'?'\\u263e Night':'\\u2600 Day';}
var s;try{s=localStorage.getItem(k)}catch(e){}set(s||'day');
document.addEventListener('click',function(e){if(e.target&&e.target.id==='tt'){
set(document.documentElement.getAttribute('data-theme')==='day'?'night':'day');}});})();"""


def _donut(dist: dict, lang: str) -> str:
    total = sum(dist.values()) or 1
    R, C = 70, 2 * math.pi * 70
    segs, cum = [], 0.0
    rows = []
    for frame, n in dist.items():
        frac = n / total
        color = _FRAME_COLOR.get(frame, "#8b949e")
        seg = frac * C
        segs.append(
            f'<circle cx="90" cy="90" r="{R}" fill="none" stroke="{color}" '
            f'stroke-width="26" stroke-dasharray="{seg:.2f} {C-seg:.2f}" '
            f'stroke-dashoffset="{-cum*C:.2f}" transform="rotate(-90 90 90)"/>')
        cum += frac
        rows.append(
            f'<div class="row"><span class="sw" style="background:{color}"></span>'
            f'{_esc(_frame_label(frame, lang))}<span class="pct">{round(frac*100)}%</span></div>')
    svg = (f'<svg width="180" height="180" viewBox="0 0 180 180" role="img" '
           f'aria-label="frame distribution">{"".join(segs)}'
           f'<text x="90" y="86" text-anchor="middle" fill="var(--text)" font-size="22" '
           f'font-weight="700">{total}</text>'
           f'<text x="90" y="104" text-anchor="middle" fill="var(--muted)" font-size="11">{_esc(_t("articles", lang))}</text></svg>')
    return f'<div class="donut-wrap">{svg}<div class="legend">{"".join(rows)}</div></div>'


def _emotion_bars(dist: dict, lang: str) -> str:
    mx = max(dist.values()) if dist else 1
    rows = []
    for emo, n in dist.items():
        color = _EMO_COLOR.get(emo, "#8b949e")
        w = round(100 * n / mx)
        rows.append(
            f'<div class="ebar"><span class="lab">{_esc(_emo_label(emo, lang))}</span>'
            f'<span class="track"><span class="fill" style="width:{w}%;background:{color}"></span></span>'
            f'<span class="n">{n}</span></div>')
    return "".join(rows) or f'<div class="empty">{_esc(_t("no_emotion", lang))}</div>'


def _sentiment(s: dict, lang: str) -> str:
    avg = s.get("avg")
    if avg is None:
        return f'<div class="empty">{_esc(_t("no_sentiment", lang))}</div>'
    pos = round((avg + 1) / 2 * 100)  # -1..1 -> 0..100
    color = "#3fb950" if avg > 0.15 else ("#f85149" if avg < -0.15 else "#d29922")
    return (f'<div class="senti"><div class="big" style="color:{color}">{avg:+.2f}</div>'
            f'<div class="gauge"><div class="pin" style="left:{pos}%"></div></div></div>'
            f'<div class="cov" style="margin-top:10px">{_esc(_t("range", lang))} '
            f'{s.get("min")} … {s.get("max")} · {s.get("n")} {_esc(_t("over_n", lang))}</div>')


def _sources_table(sources: list[dict], lang: str) -> str:
    if not sources:
        return f'<div class="empty">{_esc(_t("no_sources", lang))}</div>'
    rows = []
    for s in sources:
        f = s.get("dominant_frame")
        chip = (f'<span class="chip" style="background:{_FRAME_COLOR.get(f,"#8b949e")}">'
                f'{_esc(_frame_label(f, lang))}</span>') if f else '<span class="cov">—</span>'
        sent = s.get("avg_sentiment")
        scol = ("#3fb950" if (sent or 0) > 0.15 else "#f85149" if (sent or 0) < -0.15 else "var(--muted)")
        sval = f'<span style="color:{scol}">{sent:+.2f}</span>' if sent is not None else "—"
        name = _esc(s["source"])
        if s.get("source_id"):
            name = (f'<a href="/source/{_esc(str(s["source_id"]))}?lang={lang}" '
                    f'class="src-link">{name}</a>')
        rows.append(
            f'<tr><td>{name}</td><td class="cov">{_esc(s.get("lean") or "—")}</td>'
            f'<td>{s["articles"]}</td><td>{chip}</td>'
            f'<td class="sent-cell">{sval}</td></tr>')
    return (f'<table><thead><tr><th>{_esc(_t("th_source", lang))}</th>'
            f'<th>{_esc(_t("th_lean", lang))}</th><th>{_esc(_t("th_articles", lang))}</th>'
            f'<th>{_esc(_t("th_frame", lang))}</th><th>{_esc(_t("th_sentiment", lang))}</th></tr></thead>'
            f'<tbody>{"".join(rows)}</tbody></table>')


def render_analysis_page(data: dict, *, query: str = "", days: int = 30,
                         lang: str = "en", scope: str = "global",
                         nav_html: str = "", nav_css: str = "", request=None) -> str:
    cov = data.get("classification_coverage", {})
    note = cov.get("note")
    # Hatókör-váltó: saját nyelvterület ↔ globális korpusz (UX-teszter:
    # "a magyaron a magyar érdekes, de lehessen továbbmenni").
    def _scope_btn(key: str, label: str) -> str:
        cls = "scope-btn active" if scope == key else "scope-btn"
        return (f'<a class="{cls}" href="/analysis?lang={lang}&scope={key}'
                f'&days={days}{"&query=" + _esc(query) if query else ""}">{label}</a>')
    scope_html = ('<div class="scope-row">'
                  + _scope_btn("local", _t("scope_local", lang))
                  + _scope_btn("global", _t("scope_global", lang))
                  + '</div>')
    has_data = sum(data.get("frame_distribution", {}).values()) > 0
    method = (f'<details class="method"><summary>❓ {_esc(_t("method_q", lang))}</summary>'
              f'{_t("method_body", lang)}</details>')
    if has_data:
        body = (
            '<div class="grid">'
            f'<div class="card"><h3>{_esc(_t("framing", lang))}</h3>{_donut(data["frame_distribution"], lang)}</div>'
            f'<div class="card"><h3>{_esc(_t("emotion", lang))}</h3>{_emotion_bars(data["emotion_distribution"], lang)}</div>'
            '</div>'
            f'<div class="card"><h3>{_esc(_t("sentiment", lang))}</h3>{_sentiment(data.get("sentiment", {}), lang)}</div>'
            f'{method}'
            f'<div class="card"><h3>{_esc(_t("sources", lang))}</h3>{_sources_table(data.get("top_sources", []), lang)}</div>'
        )
    else:
        body = f'<div class="empty">{_t("empty_window", lang)}</div>'
    cov_line = f'<div class="cov">{_esc(note)}</div>' if note else ""
    day_word = _esc(_t("days", lang))
    opts = "".join(f'<option value="{d}"{" selected" if d==days else ""}>{d} {day_word}</option>'
                   for d in (7, 14, 30, 90))
    return (
        f"<!doctype html><html lang={lang}{theme_html_attr(request)}><head><meta charset=utf-8>"
        '<meta name=viewport content="width=device-width,initial-scale=1">'
        f"<title>{_esc(query)+' — ' if query else ''}Echolot Framing Analysis</title>"
        f"<style>{_CSS}{nav_css}{THEME_TOGGLE_CSS}</style></head><body>"
        + nav_html +
        '<div class=wrap>'
        f'<div class="topbar"><div class="brand"><a href="/?lang={lang}" style="color:inherit">Echolot</a> '
        f'<small>{_esc(_t("subtitle", lang))}</small></div>'
        + theme_toggle_html(lang) + '</div>'
        f'<form class="q" method="get" action="/analysis">'
        f'<input type="hidden" name="lang" value="{lang}">'
        f'<input type="hidden" name="scope" value="{_esc(scope)}">'
        f'<input type="text" name="query" value="{_esc(query)}" placeholder="{_esc(_t("placeholder", lang))}">'
        f'<select name="days">{opts}</select><button type="submit">{_esc(_t("analyze", lang))}</button></form>'
        + scope_html + cov_line + body
        + f'<div class="foot">{_esc(_t("foot", lang))}</div>'
        + f"{THEME_TOGGLE_JS}</div></body></html>"
    )
